// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SutterAnalyticsApi.Data;

#nullable disable

namespace portalApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251217213459_RemoveMustDo2025")]
    partial class RemoveMustDo2025
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SutterAnalyticsApi.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("SutterAnalyticsApi.Models.ImportJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Conflicts")
                        .HasColumnType("int");

                    b.Property<string>("DatasetKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Errors")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviewJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToCreate")
                        .HasColumnType("int");

                    b.Property<int>("ToUpdate")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.Property<int>("Unchanged")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("ImportJobs");
                });

            modelBuilder.Entity("SutterAnalyticsApi.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessGroupDn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AccessGroupName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("AssetTypeId")
                        .HasColumnType("int");

                    b.Property<string>("AutomationClassification")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BiPlatform")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("ContentHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("DataConsumers")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DataSecurityClassification")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DataSourceId")
                        .HasColumnType("int");

                    b.Property<string>("DatabaseTable")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("DbDataMart")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DbServer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DefaultAdGroupNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dependencies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DevelopmentEffortId")
                        .HasColumnType("int");

                    b.Property<int?>("DivisionId")
                        .HasColumnType("int");

                    b.Property<int?>("DomainId")
                        .HasColumnType("int");

                    b.Property<string>("EpicSecurityGroupTag")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EstimatedDevHoursId")
                        .HasColumnType("int");

                    b.Property<int?>("ExecutiveSponsorId")
                        .HasColumnType("int");

                    b.Property<bool?>("Featured")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasRls")
                        .HasColumnType("bit");

                    b.Property<string>("KeepLongTerm")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OperatingEntityId")
                        .HasColumnType("int");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int?>("PotentialToAutomateId")
                        .HasColumnType("int");

                    b.Property<int?>("PotentialToConsolidateId")
                        .HasColumnType("int");

                    b.Property<bool?>("PrivacyPhi")
                        .HasColumnType("bit");

                    b.Property<bool?>("PrivacyPii")
                        .HasColumnType("bit");

                    b.Property<string>("ProductGroup")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ProductImpactCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ProductStatusNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("RefreshFrequencyId")
                        .HasColumnType("int");

                    b.Property<string>("RegulatoryComplianceContractual")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ResourcesAnalystsId")
                        .HasColumnType("int");

                    b.Property<int?>("ResourcesDataEngineeringId")
                        .HasColumnType("int");

                    b.Property<int?>("ResourcesDevelopmentId")
                        .HasColumnType("int");

                    b.Property<int?>("ResourcesPlatformId")
                        .HasColumnType("int");

                    b.Property<string>("SourceRep")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SponsorBusinessValueId")
                        .HasColumnType("int");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("TechDeliveryManager")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserVisibilityString")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("DateAdded");

                    b.HasIndex("DevelopmentEffortId");

                    b.HasIndex("DivisionId");

                    b.HasIndex("DomainId");

                    b.HasIndex("EstimatedDevHoursId");

                    b.HasIndex("ExecutiveSponsorId");

                    b.HasIndex("Featured");

                    b.HasIndex("HasRls");

                    b.HasIndex("OperatingEntityId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PotentialToAutomateId");

                    b.HasIndex("PotentialToConsolidateId");

                    b.HasIndex("PrivacyPhi");

                    b.HasIndex("PrivacyPii");

                    b.HasIndex("ProductImpactCategoryId");

                    b.HasIndex("RefreshFrequencyId");

                    b.HasIndex("ResourcesAnalystsId");

                    b.HasIndex("ResourcesDataEngineeringId");

                    b.HasIndex("ResourcesDevelopmentId");

                    b.HasIndex("ResourcesPlatformId");

                    b.HasIndex("SponsorBusinessValueId");

                    b.HasIndex("StatusId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("SutterAnalyticsApi.Models.ItemTag", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("ItemId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ItemTags");
                });

            modelBuilder.Entity("SutterAnalyticsApi.Models.LookupValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Value");

                    b.ToTable("LookupValues");
                });

            modelBuilder.Entity("SutterAnalyticsApi.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Value");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("SutterAnalyticsApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPrincipalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserPrincipalName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SutterAnalyticsApi.Models.UserAssetOpenHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAssetOpenHistories");
                });

            modelBuilder.Entity("SutterAnalyticsApi.Models.UserFavorite", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("SutterAnalyticsApi.Models.UserLoginHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LoggedInAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserLoginHistories");
                });

            modelBuilder.Entity("SutterAnalyticsApi.Models.UserSearchHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SearchedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSearchHistories");
                });

            modelBuilder.Entity("SutterAnalyticsApi.Models.Item", b =>
                {
                    b.HasOne("SutterAnalyticsApi.Models.LookupValue", "AssetType")
                        .WithMany()
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SutterAnalyticsApi.Models.LookupValue", "DataSourceLookup")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SutterAnalyticsApi.Models.LookupValue", "DevelopmentEffortLookup")
                        .WithMany()
                        .HasForeignKey("DevelopmentEffortId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SutterAnalyticsApi.Models.LookupValue", "DivisionLookup")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SutterAnalyticsApi.Models.LookupValue", "DomainLookup")
                        .WithMany()
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SutterAnalyticsApi.Models.LookupValue", "EstimatedDevHoursLookup")
                        .WithMany()
                        .HasForeignKey("EstimatedDevHoursId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SutterAnalyticsApi.Models.Employee", "ExecutiveSponsor")
                        .WithMany()
                        .HasForeignKey("ExecutiveSponsorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SutterAnalyticsApi.Models.LookupValue", "OperatingEntityLookup")
                        .WithMany()
                        .HasForeignKey("OperatingEntityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SutterAnalyticsApi.Models.Employee", "Owner")
                        .WithMany("Items")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SutterAnalyticsApi.Models.LookupValue", "PotentialToAutomate")
                        .WithMany()
                        .HasForeignKey("PotentialToAutomateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SutterAnalyticsApi.Models.LookupValue", "PotentialToConsolidate")
                        .WithMany()
                        .HasForeignKey("PotentialToConsolidateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SutterAnalyticsApi.Models.LookupValue", "ProductImpactCategory")
                        .WithMany()
                        .HasForeignKey("ProductImpactCategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SutterAnalyticsApi.Models.LookupValue", "RefreshFrequencyLookup")
                        .WithMany()
                        .HasForeignKey("RefreshFrequencyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SutterAnalyticsApi.Models.LookupValue", "ResourcesAnalystsLookup")
                        .WithMany()
                        .HasForeignKey("ResourcesAnalystsId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SutterAnalyticsApi.Models.LookupValue", "ResourcesDataEngineeringLookup")
                        .WithMany()
                        .HasForeignKey("ResourcesDataEngineeringId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SutterAnalyticsApi.Models.LookupValue", "ResourcesDevelopmentLookup")
                        .WithMany()
                        .HasForeignKey("ResourcesDevelopmentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SutterAnalyticsApi.Models.LookupValue", "ResourcesPlatformLookup")
                        .WithMany()
                        .HasForeignKey("ResourcesPlatformId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SutterAnalyticsApi.Models.LookupValue", "SponsorBusinessValue")
                        .WithMany()
                        .HasForeignKey("SponsorBusinessValueId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SutterAnalyticsApi.Models.LookupValue", "StatusLookup")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AssetType");

                    b.Navigation("DataSourceLookup");

                    b.Navigation("DevelopmentEffortLookup");

                    b.Navigation("DivisionLookup");

                    b.Navigation("DomainLookup");

                    b.Navigation("EstimatedDevHoursLookup");

                    b.Navigation("ExecutiveSponsor");

                    b.Navigation("OperatingEntityLookup");

                    b.Navigation("Owner");

                    b.Navigation("PotentialToAutomate");

                    b.Navigation("PotentialToConsolidate");

                    b.Navigation("ProductImpactCategory");

                    b.Navigation("RefreshFrequencyLookup");

                    b.Navigation("ResourcesAnalystsLookup");

                    b.Navigation("ResourcesDataEngineeringLookup");

                    b.Navigation("ResourcesDevelopmentLookup");

                    b.Navigation("ResourcesPlatformLookup");

                    b.Navigation("SponsorBusinessValue");

                    b.Navigation("StatusLookup");
                });

            modelBuilder.Entity("SutterAnalyticsApi.Models.ItemTag", b =>
                {
                    b.HasOne("SutterAnalyticsApi.Models.Item", "Item")
                        .WithMany("ItemTags")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SutterAnalyticsApi.Models.Tag", "Tag")
                        .WithMany("ItemTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("SutterAnalyticsApi.Models.UserAssetOpenHistory", b =>
                {
                    b.HasOne("SutterAnalyticsApi.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SutterAnalyticsApi.Models.User", "User")
                        .WithMany("OpenHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SutterAnalyticsApi.Models.UserFavorite", b =>
                {
                    b.HasOne("SutterAnalyticsApi.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SutterAnalyticsApi.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SutterAnalyticsApi.Models.UserLoginHistory", b =>
                {
                    b.HasOne("SutterAnalyticsApi.Models.User", "User")
                        .WithMany("LoginHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SutterAnalyticsApi.Models.UserSearchHistory", b =>
                {
                    b.HasOne("SutterAnalyticsApi.Models.User", "User")
                        .WithMany("SearchHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SutterAnalyticsApi.Models.Employee", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SutterAnalyticsApi.Models.Item", b =>
                {
                    b.Navigation("ItemTags");
                });

            modelBuilder.Entity("SutterAnalyticsApi.Models.Tag", b =>
                {
                    b.Navigation("ItemTags");
                });

            modelBuilder.Entity("SutterAnalyticsApi.Models.User", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("LoginHistories");

                    b.Navigation("OpenHistories");

                    b.Navigation("SearchHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
